### ISSUE TITLE
Group review feedback, December 05th

### ISSUE THREAD

**Issue by v5y8** [UBC-MDS/DSCI532_World_Wide_Weapons_Report#35]
From the group review session:

notes:

- import and export in regards to which?

- tooltip should format numbers into a unit (billion $ USD or something)

- N/A countries disappear into background

- bar charts only for available year; Afghanistan looks funny.

- choose country dropdown bar should be put with the charts they affect.
 - different tabs for different charts?

year slider need to be more obvious

- blurb about research question?

	- include USA is confusing

**Comment by evelynmoorhouse** [comment]
We have added this feedback to our aggregated feedback issue #40.
