### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by PolinaRomanchenko** [UBC-MDS/DSCI532_World_Wide_Weapons_Report#36]
Hey, guys! Great dashboard, impressive functionality! But here are some suggestions on how to improve it:
1) The layout is just a tiny bit confusing at the beginning. Because when you choose the country in a drop-down menu - you can't actually see that it's changing plots. They are hidden at the bottom of the dashboard. You can easily fix this issue by moving the bottom two to the top and placing them on top of each other.  Or moving the drop-down to the bottom and putting a new topic in there i.e. 'Explore further. Choose the country'
2) Adding a small description/introduction to the dashboard about its functionality or purpose would be nice.

**Comment by evelynmoorhouse** [comment]
We have added this feedback to our aggregated feedback issue #40
