### ISSUE TITLE
Group review feedback

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/DSCI532_World_Wide_Weapons_Report#38]
Overall I think the dashboard is visually appealing and is useful for exploring the data. Well done! Here are a few suggestions I discussed with Serg:

- I think you should try to make it really clear what each filter/action button does. 
    - For example it took me some time to realize that the country drop down only applied to the bottom two plots
    - I would try and align each filter so that it is parallel with the plot it effects
    - one way to achieve this would be by expanding the sidebar all the way down
- For countries that have no value or have been excluded in the map it would be nice if they had a gray colour instead of white

I have also outlined a few other suggestions in the picture below

<img width="712" alt="Screen Shot 2019-12-05 at 2 58 22 PM" src="https://user-images.githubusercontent.com/18248949/70281664-7bdbcd80-1770-11ea-9936-fd7dd36959e0.png">

**Comment by evelynmoorhouse** [comment]
We have added this feedback to our aggregated feedback issue.
